spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    username: oyatrij
    password: 4orescout
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
